services:
  drone-srcb:
    build: .
    environment:
      API_ID: $API_ID  
      API_HASH: $API_HASH  
      BOT_TOKEN: $BOT_TOKEN
      DB_CHANNEL_ID: $DB_CHANNEL
      IS_PRIVATE: $IS_PRIVATE
      UPDATE_CHANNEL: $UPDATE_CHANNEL
      LOG_CHANNEL: $LOG_CHANNEL
      OWNER_ID: $OWNER_ID
    ports:
      - 8080
    resources:
      cpu: 1000m
      memory: 3Gi
